version: '3.7'

services:
    artbot:
        build:
            context: .
            dockerfile: Dockerfile
        command: flask run -h 0.0.0.0
        volumes:
            - .:/usr/src/app
        ports:
            - 5001:5000
        environment:
            - FLASK_ENV=development
            - FLASK_APP=web.app:create_app
            - APP_SETTINGS=web.settings.DevConfig
            - INITIAL_ADMIN_PASSWORD=TEMP
            - DATABASE_URL=postgresql://postgres:postgres@artbot-db:5432/artbot_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@artbot-db:5432/artbot_test
            - MAIL_SERVER=maildev
            - MAIL_PORT=25
            - MAIL_DEFAULT_SENDER=ccl-artbot@gmail.com
            - AWS_SERVER=localstack
            - AWS_PORT=4566
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=TEMP
            - AWS_SECRET_ACCESS_KEY=TEMP
            - IMAGE_BUCKET=dataimages
        depends_on:
            - artbot-db
            - localstack
            - maildev

    artbot-db:
        build:
            context: ./db
            dockerfile: Dockerfile
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres


    localstack:
        image: localstack/localstack
        ports:
            - 4566:4566
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=TEMP #Should match above
            - AWS_SECRET_ACCESS_KEY=TEMP
            - SERVICES=s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - "./.localstack:/tmp/localstack"
            - "./dev_deploy:/docker-entrypoint-initaws.d" #Runs startup scripts

    maildev:
        image: djfarrelly/maildev
        ports:
            - 1080:80
