"""index user_id

Revision ID: 2c6e19531f96
Revises: 4187ace743a2
Create Date: 2019-11-16 13:18:24.646582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e19531f96'
down_revision = '4187ace743a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artpieces_user_id'), 'artpieces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artpieces_user_id'), table_name='artpieces')
    # ### end Alembic commands ###
