"""empty message
Revision ID: 388b0bac0e9b
Revises: 8386df60ac9f
Create Date: 2019-11-07 23:25:49.772012
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388b0bac0e9b'
down_revision = '8386df60ac9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artpieces', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artpieces', 'photo')
    # ### end Alembic commands ###
