"""empty message

Revision ID: 4cca6239c5f7
Revises: e6dac6dcaf71
Create Date: 2019-10-06 16:14:34.820771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cca6239c5f7'
down_revision = 'e6dac6dcaf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artpieces', sa.Column('picture', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artpieces', 'picture')
    # ### end Alembic commands ###
