"""add lab_objects table

Revision ID: 5232f48e49c1
Revises: ba196fd05ecc
Create Date: 2021-07-29 05:46:07.014025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5232f48e49c1'
down_revision = 'ba196fd05ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('obj_class', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_objects_name'), 'lab_objects', ['name'], unique=True)
    op.create_table('lab_object_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('obj_property', sa.String(length=50), nullable=False),
    sa.Column('obj_property_units', sa.String(length=20), nullable=True),
    sa.Column('property_value_num', sa.Float(), nullable=True),
    sa.Column('property_value_str', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['lab_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_object_properties')
    op.drop_index(op.f('ix_lab_objects_name'), table_name='lab_objects')
    op.drop_table('lab_objects')
    # ### end Alembic commands ###
