"""color-migration

Revision ID: 56c76cb1127d
Revises: eeafa5624ec7
Create Date: 2020-02-10 17:52:01.666608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c76cb1127d'
down_revision = 'eeafa5624ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacterial_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('red', sa.SmallInteger(), nullable=False),
    sa.Column('green', sa.SmallInteger(), nullable=False),
    sa.Column('blue', sa.SmallInteger(), nullable=False),
    sa.Column('opacity', sa.SmallInteger(), nullable=False),
    sa.Column('biobrick_id', sa.String(length=30), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    op.execute(("INSERT INTO bacterial_colors "
        "(name, red, green, blue, opacity, biobrick_id, in_use) "
        "VALUES ('pink', 255, 192, 203, 1, 'BBa_E1010', TRUE), "
        "('blue', 0, 0, 255, 1, 'BBa_K592009', TRUE), "
        "('teal', 0, 128, 128, 1, 'BBa_K592011', TRUE), "
        "('peach', 255, 165, 0, 1, 'BBa_E2050', TRUE), "
        "('fluorescent yellow', 255, 255, 0, 1, 'BBa_K1033916', TRUE)"))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bacterial_colors')
    # ### end Alembic commands ###
