"""Email failure

Revision ID: 802864c6122e
Revises: 2c6e19531f96
Create Date: 2019-11-16 16:33:44.484607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802864c6122e'
down_revision = '2c6e19531f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailfailures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artpiece_id', sa.Integer(), nullable=True),
    sa.Column('failure_state', sa.Enum('s_confirmation', 'bioart_completion', name='emailfailurestate'), nullable=False),
    sa.Column('error_msg', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['artpiece_id'], ['artpieces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailfailures')
    # ### end Alembic commands ###
