"""empty message

Revision ID: c24e32957323
Revises: 
Create Date: 2019-10-06 00:08:45.239680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24e32957323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('site_vars')
    op.alter_column('artpieces', 'art',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artpieces', 'art',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('site_vars',
    sa.Column('var', sa.VARCHAR(), nullable=False),
    sa.Column('val', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('var')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
