"""artpiece_slug

Revision ID: eeafa5624ec7
Revises: a20324cb6d44
Create Date: 2020-02-09 05:42:17.894691

"""
# revision identifiers, used by Alembic.
revision = 'eeafa5624ec7'
down_revision = 'a20324cb6d44'
branch_labels = None
depends_on = None


from slugify import slugify
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from migrations.utils.session import session_scope

Base = declarative_base()

class ArtpieceModel(Base):
    __tablename__ = 'artpieces'

    id = sa.Column(sa.Integer, primary_key=True)
    slug = sa.Column(sa.String(60), nullable=True, unique=True, index=True)
    title = sa.Column(sa.String(50), nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artpieces', sa.Column('slug', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_artpieces_slug'), 'artpieces', ['slug'], unique=True)
    # ### end Alembic commands ###
    with session_scope() as session:
        artpieces = session.query(ArtpieceModel).all()
        # create unique slugs
        slug_counts = dict()
        for artpiece in artpieces:
            slug = slugify(artpiece.title)
            count = (slug_counts.get(slug) or 0) + 1
            artpiece.slug = f'{slug}#{count}'
            slug_counts[slug] = count

    op.alter_column('artpieces', 'slug', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artpieces_slug'), table_name='artpieces')
    op.drop_column('artpieces', 'slug')
    # ### end Alembic commands ###
