"""empty message

Revision ID: fca4d39d6f19
Revises: 8386df60ac9f
Create Date: 2019-10-31 13:06:26.681806

"""

# revision identifiers, used by Alembic.
revision = 'fca4d39d6f19'
down_revision = '8386df60ac9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from migrations.utils.session import session_scope
from migrations.utils.image import decode_art_to_image

Base = declarative_base()

COLOR_SCHEME = {
    'pink': (255,192,203,1)
    ,'blue': (0,0,255,1)
    ,'teal': (0,128,128,1)
    ,'orange': (255,165,0,1)
    ,'yellow': (255,255,0,1)
}

class ArtpieceModel(Base):
    __tablename__ = 'artpieces'

    id = sa.Column(sa.Integer, primary_key=True)
    art = sa.Column(sa.JSON(), nullable=False, name='art_encoding')
    raw_image = sa.Column(sa.LargeBinary(), nullable=True)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_vars')
    # ### end Alembic commands ###
    op.alter_column('artpieces', 'art', new_column_name='art_encoding', type_=sa.JSON(),
            postgresql_using='art::json', nullable=False)
    op.alter_column('artpieces', 'picture', new_column_name='raw_image', nullable=True)
    op.alter_column('artpieces', 'status', new_column_name='submission_status', nullable=False)
    op.alter_column('artpieces', 'title', nullable=False)
    op.alter_column('artpieces', 'submit_date', nullable=False)

    with session_scope() as session:
        artpieces = session.query(ArtpieceModel).filter(ArtpieceModel.raw_image == None).all()
        for artpiece in artpieces:
            artpiece.raw_image = decode_art_to_image(artpiece.art, COLOR_SCHEME)

    op.alter_column('artpieces', 'raw_image', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_vars',
    sa.Column('var', sa.VARCHAR(), nullable=False),
    sa.Column('val', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('var')
    )
    # ### end Alembic commands ###
    op.alter_column('artpieces', 'art_encoding', new_column_name='art', type_=sa.String()
            , nullable=True)
    op.alter_column('artpieces', 'raw_image', new_column_name='picture', nullable=True)
    op.alter_column('artpieces', 'submission_status', new_column_name='status', nullable=True)
    op.alter_column('artpieces', 'title', nullable=True)
    op.alter_column('artpieces', 'submit_date', nullable=True)
